name       : ocaml
version    : 4.07.0
release    : 8
homepage   : http://ocaml.org/
source     :
    - http://caml.inria.fr/pub/distrib/ocaml-4.07/ocaml-4.07.0.tar.xz : f45bf720aadf5c6408400d5179b92ea7130b7e55e501a1768c2d136ef69f9f0f
license    :
    - QPL-1.0
    - GPL-2.0
component  : programming
summary    : A functional language with OO extensions
description: |
    OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles
builddeps  :
    - pkgconfig(x11)
setup      : |
    ./configure -prefix /usr \
                -libdir %libdir%/ocaml \
                -mandir /usr/share/man
build      : |
    %make world.opt
install    : |
    %make_install

    export compiler_libs="$installdir/%libdir%/ocaml/compiler-libs"
    mkdir -p "$compiler_libs"/{parsing,typing,utils}
    cp parsing/*.{cmi,cmo,cmx,ml,mli,mll,o} "$compiler_libs"/parsing
    cp typing/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/typing
    cp utils/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/utils

    rm -f "$compiler_libs"/typing/outcometree.{cmi,mli}
