name       : ocaml
version    : 4.08.0
release    : 11
homepage   : http://ocaml.org/
source     :
    - https://github.com/ocaml/ocaml/archive/4.08.0.tar.gz : c8ff78d010cb037ac6d6729e40ebdbee109218899007ef23a20b8f459ac186d6
license    :
    - QPL-1.0
    - GPL-2.0
component  : programming
summary    : A functional language with OO extensions
description: |
    OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles
builddeps  :
    - pkgconfig(x11)
setup      : |
    ./configure -prefix /usr \
                -libdir %libdir%/ocaml \
                -mandir /usr/share/man
build      : |
    %make world.opt
install    : |
    %make_install

    export compiler_libs="$installdir/%libdir%/ocaml/compiler-libs"
    mkdir -p "$compiler_libs"/{parsing,typing,utils}
    cp parsing/*.{cmi,cmo,cmx,ml,mli,mll,o} "$compiler_libs"/parsing
    cp typing/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/typing
    cp utils/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/utils

    rm -f "$compiler_libs"/typing/outcometree.{cmi,mli}
