name       : ocaml
version    : 4.14.0
release    : 20
homepage   : http://ocaml.org/
source     :
    - https://github.com/ocaml/ocaml/archive/refs/tags/4.14.0.tar.gz : 39f44260382f28d1054c5f9d8bf4753cb7ad64027da792f7938344544da155e8
license    :
    - QPL-1.0
    - GPL-2.0
component  : programming
summary    : A functional language with OO extensions
description: |
    OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles
strip      : no
builddeps  :
    - pkgconfig(x11)
setup      : |
    ./configure -prefix /usr \
                -libdir %libdir%/ocaml \
                -mandir /usr/share/man \
                -disable-force-safe-string
build      : |
    %make world.opt
install    : |
    %make_install

    export compiler_libs="$installdir/%libdir%/ocaml/compiler-libs"
    mkdir -p "$compiler_libs"/{parsing,typing,utils}
    cp parsing/*.{cmi,cmo,cmx,ml,mli,mll,o} "$compiler_libs"/parsing
    cp typing/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/typing
    cp utils/*.{cmi,cmo,cmx,ml,mli,o} "$compiler_libs"/utils

    rm -f "$compiler_libs"/typing/outcometree.{cmi,mli}
